# Importing Libraries and Dataset

In [1]:
# importing the required libraries/Modules

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
car_data = pd.read_csv("car_data.csv")

# Dataset Explore

In [3]:
car_data.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [4]:
car_data.tail()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [5]:
car_data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [6]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

In [7]:
car_data.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [8]:
car_data.describe()

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

In [10]:
print(car_data)

          Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0
1          BMW    1 Series  2011     premium unleaded (required)      300.0
2          BMW    1 Series  2011     premium unleaded (required)      300.0
3          BMW    1 Series  2011     premium unleaded (required)      230.0
4          BMW    1 Series  2011     premium unleaded (required)      230.0
...        ...         ...   ...                             ...        ...
11909    Acura         ZDX  2012     premium unleaded (required)      300.0
11910    Acura         ZDX  2012     premium unleaded (required)      300.0
11911    Acura         ZDX  2012     premium unleaded (required)      300.0
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0
11913  Lincoln      Zephyr  2006                regular unleaded      221.0

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0
1                   6.0            MANUAL   rear wheel drive              2.0
2                   6.0            MANUAL   rear wheel drive              2.0
3                   6.0            MANUAL   rear wheel drive              2.0
4                   6.0            MANUAL   rear wheel drive              2.0
...                 ...               ...                ...              ...
11909               6.0         AUTOMATIC    all wheel drive              4.0
11910               6.0         AUTOMATIC    all wheel drive              4.0
11911               6.0         AUTOMATIC    all wheel drive              4.0
11912               6.0         AUTOMATIC    all wheel drive              4.0
11913               6.0         AUTOMATIC  front wheel drive              4.0

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe
1                         Luxury,Performance      Compact    Convertible
2                    Luxury,High-Performance      Compact          Coupe
3                         Luxury,Performance      Compact          Coupe
4                                     Luxury      Compact    Convertible
...                                      ...          ...            ...
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11913                                 Luxury      Midsize          Sedan

       highway MPG  city mpg  Popularity   MSRP
0               26        19        3916  46135
1               28        19        3916  40650
2               28        20        3916  36350
3               28        18        3916  29450
4               28        18        3916  34500
...            ...       ...         ...    ...
11909           23        16         204  46120
11910           23        16         204  56670
11911           23        16         204  50620
11912           23        16         204  50920
11913           26        17          61  28995

[11914 rows x 16 columns]

In [11]:
car_data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool